# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adam Jones
email: adam.jones@codethink.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my blog, where i'll share posts regarding my work, ideas
  and life. I hope you find it useful at some point!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://adamjones.online" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adds68
github_username:  wetrain

enabled: all
enabled:
  - categories
enabled:
  - year
  - month
  - tags

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

category-list: [Code-snips, Editors, Math, Unix, Python, Vim, BuildStream, Conferences]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
